### PR TITLE
Feature changes for communities

### PR DESCRIPTION
**Pull request by Dusteh**
Changed the math on how we figure out what ratio is good for communities.

### CODE REVIEW

**Review by noisesmith — COMMENTED** [review]
I'm puzzled by why we would want a number that gets larger with a larger input, where the previous version made the number smaller with larger inputs?

**Comment by noisesmith** [comment]
also - another point of reference - there is already a magic number scaling the scale factor https://github.com/littlebird/owl/blob/master/src/clj/owl/modularity.clj#L102

it could be that inverting the influence of the scale factor is something we need, but I'd be interested to hear the explanation for that choice?

**Comment by prismofeverything** [comment]
Hello! Have you tested this change? Does it have the desired outcome? What problem are you trying to solve?

I admit I am fond of this algorithm and would be happy to see it improve : )

**Comment by jeffgodd** [comment]
Yes, I've tested this PR and I am not satisfied it is an improvement.  The goal of reducing the ratio factor mentioned by noisesmith from its original of 0.5 to 0.4 in April of 2016 was to reduce the number of communities.  It had the desired effect.  This was also the goal of the proposed change here.  Instead, I will adjust this down a little further and see what the results are.

**Comment by jeffgodd** [comment]
Closing until we find a plan B

**Pull request closed without merging**
